config/routes.rb
DiscoveryProgramme::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :users
  root :to => 'pages#home'
  
  resources :users, :bibliographies, :blade_profiles, :butt_shapes, :collections, :contexts, :cross_sections, :edge_forms, :edge_shapes, :face_shapes, :haftings, :macros, :prime_treatments, :profiles, :re_uses, :use_wears, :stray_axes
  resources :linkages, :pictures, :minerals, :chemical_compositions
  resources :axe_masters do
    collection { post :search, to: 'axe_masters#index'
       get :search, to: 'axe_masters#index' }
  end
  
  match '/list' => 'pages#list'
  match '/help' => 'pages#help'

  get "axe_masters/search"

end

app/models/axe_master.rb
class AxeMaster < ActiveRecord::Base  
  attr_accessible :confirmed, :seq_no, :dating_information, :museum_ref, :collections_id, :current_location, :townland, :area, :county, :discovery_circumstances, :context_id, :from_year, :to_year, :map_reference, :temp_map_reference, :NGR_x_axis, :NGR_y_axis, :ordinance_datum, :object_type, :length, :width, :thickness, :weight, :face_shape_id, :cross_section_id, :edge_shape_id, :profile_id, :blade_profile_id, :butt_shape_id, :facet_1_right, :facet_2_right, :facet_1_left, :facet_2_left, :prime_treatment_id, :blade_ground, :sides_ground, :faces_ground, :butt_ground, :blade_polished, :sides_polished, :faces_polished, :butt_polished, :hafting_id, :description, :macro_id, :micro_id, :specific_gravity, :petrology, :comments, :drawn, :archival_complete, :object_comp, :petrology_comp, :mapping_comp, :photographed, :axe_cored, :barony, :parish, :hoard, :new_museum_ref, :catalogue_ref, :site_type, :secure_context, :feature_context_details, :associated_artifacts, :associated_features, :use_wear_id, :deliberate_breaking, :re_use_id, :edge_form_id, :edge_form, :mineral_identification_method, :chemical_composition_method, :object_status, :incomplete_description, :roughout_description, :incomplete_details, :roughout_details, :minature, :user_id, :image  
  validates_uniqueness_of :seq_no
  
  has_many :linkages, :dependent => :destroy, :foreign_key => "sequence_no", :primary_key => "seq_no"
  has_many :bibliographies, :class_name => "Bibliography", :through => :linkages
  has_many :pictures, :dependent => :destroy, :foreign_key => "seq_no", :primary_key => "seq_no"
  has_many :location_links, foreign_key: "seq_no", primary_key: "seq_no"
  has_many :townlands, class_name: "Townland", through: :location_links

  has_one :context, :foreign_key => :code, :primary_key => :context_id
  has_one :face_shape, :foreign_key => :code, :primary_key => :face_shape_id
  has_one :cross_section, :foreign_key => :code, :primary_key => :cross_section_id
  has_one :edge_shape, :foreign_key => :code, :primary_key => :edge_shape_id
  has_one :profile, :foreign_key => "code", :primary_key => "profile_id"
  has_one :blade_profile, :foreign_key => :code, :primary_key => :blade_profile_id
  has_one :butt_shape, :foreign_key => :code, :primary_key => :butt_shape_id
  has_one :prime_treatment, :foreign_key => :code, :primary_key => :prime_treatment_id
  has_one :hafting, :foreign_key => :code, :primary_key => :hafting_id
  has_one :macro, :foreign_key => :macro_id, :primary_key => :macro_id
  has_one :use_wear, :foreign_key => :code, :primary_key => :use_wear_id
  has_one :re_use, :foreign_key => :code, :primary_key => :re_use_id
  has_one :edge_form, :foreign_key => :code, :primary_key => :edge_form_id
  has_one :collection, :foreign_key => :collection_title, :primary_key => :collection_title
  has_one :user, :foreign_key => "id", :primary_key => "user_id"

  def self.ransackable_attributes(auth_object = nil)
      super & ["sequence_no", "museum_ref", "collections_id", "townland", "area", "county", "discovery_circumstances", "context_id", "from_year", "to_year", "map_reference", "temp_map_reference", "'NGR_x_axis'", "'NGR_y_axis'", "ordinance_datum", "object_type", "length", "width", "thickness", "weight", "face_shape_id", "cross_section_id", "edge_shape_id", "profile_id", "blade_profile_id", "butt_shape_id", "facet_1_right", "facet_2_right", "facet_1_left", "facet_2_left", "prime_treatment_id", "blade_ground", "sides_ground", "faces_ground", "butt_ground", "blade_polished", "sides_polished", "faces_polished", "butt_polished", "hafting_id", "description", "macro_id", "micro_id", "specific_gravity", "petrology", "drawn", "archival_complete", "object_comp", "petrology_comp", "mapping_comp", "photographed", "axe_cored", "barony", "parish", "hoard", "new_museum_ref", "catalogue_ref", "site_type", "secure_context", "feature_context_details", "associated_artifacts", "associated_features", "dating_information", "use_wear_id", "deliberate_breaking", "re_use_id", "edge_form_id", "mineral_identification_method", "chemical_composition_method", "object_status", "incomplete_description", "roughout_description", "incomplete_details", "roughout_details", "minature"]

  end
  
  after_initialize :default_values

  comma :researcher do
    seq_no
    museum_ref
    collections_id
    townland
    area
    county
    discovery_circumstances
    context_id
    from_year
    to_year
    map_reference
    temp_map_reference
    "NGR_x_axis"
    "NGR_y_axis"
    ordinance_datum
    object_type
    length
    width
    thickness
    weight
    face_shape_id
    cross_section_id
    edge_shape_id
    profile_id
    blade_profile_id
    butt_shape_id
    facet_1_right
    facet_2_right
    facet_1_left
    facet_2_left
    prime_treatment_id
    blade_ground
    sides_ground
    faces_ground
    butt_ground
    blade_polished
    sides_polished
    faces_polished
    butt_polished
    hafting_id
    description
    macro_id
    micro_id
    specific_gravity
    petrology
    drawn
    archival_complete
    object_comp
    petrology_comp
    mapping_comp
    photographed
    axe_cored
    barony
    parish
    hoard
    new_museum_ref   
    catalogue_ref
    site_type
    secure_context
    feature_context_details
    associated_artifacts
    associated_features
    dating_information
    use_wear_id
    deliberate_breaking
    re_use_id
    edge_form_id
    mineral_identification_method
    chemical_composition_method
    object_status
    incomplete_description
    roughout_description
    incomplete_details
    roughout_details
    minature
    
  end
  
  comma do
    seq_no
    museum_ref
    collections_id
    current_location
    townland
    area
    county
    discovery_circumstances
    context_id
    from_year
    to_year
    map_reference
    temp_map_reference
    "NGR_x_axis"
    "NGR_y_axis"
    ordinance_datum
    object_type
    length
    width
    thickness
    weight
    face_shape_id
    cross_section_id
    edge_shape_id
    profile_id
    blade_profile_id
    butt_shape_id
    facet_1_right
    facet_2_right
    facet_1_left
    facet_2_left
    prime_treatment_id
    blade_ground
    sides_ground
    faces_ground
    butt_ground
    blade_polished
    sides_polished
    faces_polished
    butt_polished
    hafting_id
    description
    macro_id
    micro_id
    specific_gravity
    petrology
    comments
    drawn
    archival_complete
    object_comp
    petrology_comp
    mapping_comp
    photographed
    axe_cored
    barony
    parish
    hoard
    new_museum_ref   
    catalogue_ref
    site_type
    secure_context
    feature_context_details
    associated_artifacts
    associated_features
    dating_information
    use_wear_id
    deliberate_breaking
    re_use_id
    edge_form_id
    mineral_identification_method
    chemical_composition_method
    object_status
    incomplete_description
    roughout_description
    incomplete_details
    roughout_details
    minature    
  end
  
  
private
    def default_values
      self.confirmed ||= false
      self.sequence_no ||= self.seq_no.to_i
      #self.seq_no ||= AxeMaster.order("seq_no desc").first.seq_no.to_i + 1
    end
end

app/controllers/axe_masters_controller.rb
class AxeMastersController < ApplicationController
  load_and_authorize_resource
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  
  def index
    @q = AxeMaster.ransack(params[:q], :confirmed => true)
    @axe_masters = @q.result.paginate(:page => params[:page], :per_page => 100)
    
    @q.build_condition if @q.conditions.empty?
    @q.build_sort if @q.sorts.empty?   

    if params[:search].eql?("xml")
      if current_user.admin || current_user.researcher
        send_data @axe_masters.to_xml, :filename => "admin-axe.xml"       
      else
        send_data @axe_masters.to_xml(:except => [:comments, :current_location]), :filename => "axe.xml" 
      end
    elsif params[:search].eql?("csv")
      if current_user.admin || current_user.researcher
        send_data @axe_masters.to_comma, :style => :researcher, :col_sep => ',', :filename => "admin-axe.csv" 
      else
        send_data @axe_masters.to_comma, :col_sep => ',', :filename => "axe.csv"
      end
    end
  end

  def show
    @axe_master = AxeMaster.find(params[:id])
    @linkage = Linkage.new
    @picture = Picture.new

     respond_to do |format|
      format.html
      format.csv { 
        if current_user.admin || current_user.researcher
          send_data @axe_master.to_comma, :style => :researcher, :col_sep => ',', :filename => "admin-axe_search.csv" 
        else
          send_data @axe_master.to_comma, :col_sep => ',', :filename => "axe_search.csv"
        end
      }
      format.xml { 
        if current_user.admin || current_user.researcher
          send_data @axe_master.to_xml, :filename => "admin-axe.xml"       
        else
          send_data @axe_master.to_xml(:except => [:comments, :current_location]), :filename => "axe.xml" 
        end
      }
    end
  end
  
  def edit
    
  end

  def new
    if signed_in?
      @axe_master = current_user.axe_masters.build
    else
      flash[:notice] = "You must be signed in to continue"
      redirect_to root_path
    end
  end
   
  def create
    @axe_master = current_user.axe_masters.build(params[:axe_master])
    @axe_master[:seq_no] = get_seq_no((AxeMaster.order("sequence_no desc").first.seq_no).to_i+1)
    if @axe_master.save
      flash[:success] = "Your record has been submited for approval."
      UserMailer.signupConfirmation(current_user, "Axe", @axe_master).deliver
      redirect_to root_path
    else
      flash[:error] = "Record did not save"
      redirect_to :back
    end
  end

  def update
    @axe_master = AxeMaster.find(params[:id])

    if @axe_master.update_attributes(params[:axe_master])
      flash[:notice] = "Record was successfully updated."
      redirect_to axe_master_path(@axe_master)
    end
  end
  
  def destroy
    @axe_master = AxeMaster.find(params[:id])
    @axe_master.destroy
    flash[:alert] = "Axe record deleted!"
    redirect_to axe_masters_path
  end
  
  def search
    index
    render :index
  end
  
private
  def get_seq_no(search)
    @test = AxeMaster.find(:all, :conditions => {:seq_no => search.to_s})
    if @test.empty?
      return search.to_s
    else
      get_seq_no(search+1)
    end
  end
  
  def record_not_found
    redirect_to axe_masters_path
  end
end

app/helpers/axe_masters_helper.rb
module AxeMastersHelper
end

app/views/axe_masters/_condition_fields.html.erb
<div class="field">
	<div class="row-fluid">
		<%= f.attribute_fields do |a| %>
			<span class="span4"><%= a.attribute_select%></span>
		<% end %>
		<span class="span2"><%= f.predicate_select(:only => [:matches, :lt, :gt, :cont, :start, :end, :null, :not_null]) %></span>
		<%= f.value_fields do |v| %>
			<span class="span4"><%= v.text_field :value %></span>
		<% end %>
		<span class="span2"><%= link_to "remove", '#', class: "remove_fields" %></span>
	</div>
</div>

app/views/axe_masters/_form.html.erb
<%= simple_form_for @axe_master, :html => { :class => 'form-horizontal well',:multipart => true } do |f| %>
		<fieldset>
		  <legend>Archival & Contextual Data</legend>
			<%= f.input :museum_ref %>
			<%= f.input :new_museum_ref %>
			<%= f.input :collections_id, :as => :select, :collection => Hash[Collection.all.map{|b| [b.collection_title,b.id]}]  %>
			<%= f.input :townland %>
			<%= f.input :area %>
		    <%= f.input :barony %>
		   	<%= f.input :parish %>
			<%= f.input :county %>
			<%= f.input :map_reference %>	
			<%= f.input :temp_map_reference %>	
			<%= f.input :NGR_x_axis %>	
			<%= f.input :NGR_y_axis %>	
			<%= f.input :ordinance_datum %>	
			<%= f.input :discovery_circumstances, :class => 'text_block' %>
			<%= f.input :hoard %>	
			<%= f.input :context_id, :as => :select, :collection => Hash[::Context.all.collect{|b| [b.description,b.id]}] %>		
			<%= f.input :from_year %>	
			<%= f.input :drawn, :as => :radio_buttons %>
			<%= f.input :archival_complete, :as => :radio_buttons %>
			<%= f.input :object_comp, :as => :radio_buttons %>
			<%= f.input :petrology_comp, :as => :radio_buttons %>
			<%= f.input :mapping_comp, :as => :radio_buttons %>
		</fieldset>
	
	<% if can? :destroy, AxeMaster %>
		<fieldset>
			<legend>Admin Inputs</legend>
			<%= f.input :current_location %>
			<%= f.input :comments %>
		</fieldset>
	<% end %>
	
		<fieldset>
			<legend>Physical Characteristics</legend>
			<%= f.input :object_type %>
			<%= f.input :minature %>
			<%= f.input :object_status %>
			<%= f.input :incomplete_description %>
			<%= f.input :roughout_description %>
			<%= f.input :incomplete_details %>
			<%= f.input :roughout_details %>
			<%= f.input :face_shape_id, :as => :select, :collection => Hash[FaceShape.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :cross_section_id, :as => :select, :collection => Hash[CrossSection.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :edge_shape_id, :as => :select, :collection => Hash[EdgeShape.all.map{|b| [b.description,b.code]}]%>
			<%= f.input :profile_id, :as => :select, :collection => Hash[Profile.all.map{|b| [b.description,b.code]}] %>	
			<%= f.input :blade_profile_id, :as => :select, :collection => Hash[BladeProfile.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :butt_shape_id, :as => :select, :collection => Hash[ButtShape.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :use_wear_id, :as => :select, :collection => Hash[UseWear.all.map{|b| [b.description,b.code]}]  %>
			<%= f.input :deliberate_breaking %>
			<%= f.input :re_use_id, :as => :select, :collection => Hash[ReUse.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :edge_form_id, :as => :select, :collection => Hash[EdgeForm.all.map{|b| [b.description,b.code]}] %>		
			<%= f.input :hafting_id, :as => :select, :collection => Hash[Hafting.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :length %>
			<%= f.input :width %>
			<%= f.input :thickness %>
			<%= f.input :weight %>	
			<%= f.input :prime_treatment_id, :as => :select, :collection => Hash[PrimeTreatment.all.map{|b| [b.description,b.code]}] %>
			<%= f.input :facet_1_right, :as => :radio_buttons %>
			<%= f.input :facet_2_right, :as => :radio_buttons %>
			<%= f.input :facet_1_left, :as => :radio_buttons %>
			<%= f.input :facet_2_left, :as => :radio_buttons %>
			<%= f.input :blade_ground, :as => :radio_buttons %>
			<%= f.input :sides_ground, :as => :radio_buttons %>
			<%= f.input :faces_ground, :as => :radio_buttons %>
			<%= f.input :butt_ground, :as => :radio_buttons %>
			<%= f.input :blade_polished, :as => :radio_buttons %>
			<%= f.input :sides_polished, :as => :radio_buttons %>
			<%= f.input :faces_polished, :as => :radio_buttons %>
			<%= f.input :butt_polished, :as => :radio_buttons %>
		</fieldset>

		<fieldset>
			<legend>Petrology</legend>
			<%= f.input :macro_id, :as => :select, :collection => Hash[Macro.all.map{|b| [b.total,b.macro_id]}]  %>	
			<%= f.input :micro_id %>
			<%= f.input :specific_gravity %>
			<%= f.input :petrology %>
			<%= f.input :axe_cored, :as => :radio_buttons %>

			<%= f.input :mineral_identification_method %>	
			<%= f.input :chemical_composition_method %>		
		</fieldset>

		<fieldset>
			<legend>Archaeological Excavation</legend>
			<%= f.input :site_type %>
			<%= f.input :secure_context %>
			<%= f.input :feature_context_details %>
			<%= f.input :associated_artifacts %>
			<%= f.input :associated_features %>
			<%= f.input :dating_information %>
		</fieldset>


  <div class="form-actions">
    <%= f.button :submit, "Submit Record", :class => 'btn-primary', :id => "Create" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                axe_masters_path, :class => 'btn' %>
  </div>
<% end %>

app/views/axe_masters/_search_form.html.erb
<h2>Search Form</h2>
<%= search_form_for @q, :html => { :class => 'well form-search' }, url: search_axe_masters_path, method: :post do |f| %>
  <fieldset>
	<legend>Condition fields</legend>
    <%= f.condition_fields do |c| %>
      <div class="field">
        <div class="row-fluid">
          <%= c.attribute_fields do |a| %>
            <span class="span4"><%= a.attribute_select associations: [:seq_no] %></span>
          <% end %>
          <span class="span2"><%= c.predicate_select(:only => [:matches, :lt, :gt, :cont, :start, :end, :null, :not_null]) %></span>
          <%= c.value_fields do |v| %>
            <span class="span4"><%= v.text_field :value %></span>
          <% end %>
          <span class="span2"><%= link_to "remove", '#', class: "remove_fields" %></span>
        </div>
      </div>
    <% end %>
    <p><%= link_to_add_fields "Add Conditions", f, :condition %></p> 
  </fieldset>

  <div class="field">
    <fieldset>
      <legend>Sorting</legend>
      <%= f.sort_fields do |s| %>
        <div class="row-fluid">
          <span class="field">
            <div class="span8"><%= s.sort_select associations: [:seq_no] %></div><div class="span4"> <%= link_to "remove", '#', class: "remove_fields" %></div><br />
          </span>
        </div>
        <% end %>
      <%= link_to_add_fields "Add Sort", f, :sort %>
    </fieldset>    
  </div>

  <div class="form-actions">
    <%= f.button :search, :class => 'btn-primary', :name => "search", :id => "search", :value => "html" %>
    <div class="pull-right">
      <% if current_user && current_user.confirmed %>
  	    <strong>Export to: </strong>
  	    	<%= f.button :xml, :class => 'btn-info', :name => "search", :id => "search", :value => "xml" %>
  	   		<%= f.button :csv, :class => 'btn-info', :name => "search", :id => "search", :value => "csv" %>
      <% end %>
 	  </div>
  </div>
<% end %>

app/views/axe_masters/_sort_fields.html.erb
<div class="row-fluid">
	<span class="field">
		<div class="span8">
			<%= f.sort_select associations: [:seq_no] %></div><div class="span4"> <%= link_to "remove", '#', class: "remove_fields" %>
		</div>
		<br />
	</span>
</div>

app/views/axe_masters/edit.html.erb
<%- model_class = AxeMaster -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/axe_masters/index.html.erb
<%- model_class = AxeMaster -%>
<%= render 'search_form' %>
<div class="spacer"></div>
<div class="page-header">
	<h1>Axe Records</h1>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="pagination pagination-centered">
			<%= will_paginate @axe_masters %>
		</div>
	</div>
</div>
<div class="spacer hidden-desktop"></div>

<div class="row-fluid">
	<div class="span12">
		<div class="well">
			<table class="table table-striped">
				<thead>
					<tr>
						<th><%= sort_link @q, :sequence_no, "Sequence No" %></th>
						<th><%= sort_link @q, :museum_ref, "Museum Reference" %></th>
						<th class="hidden-phone"><%= sort_link @q, :collection, "Collection" %></th>
						<th class="hidden-phone"><%= sort_link @q, :townland, "Townland" %></th>
						<th class="hidden-phone"><%= sort_link @q, :county, "County" %></th>
						<th class="hidden-phone"><%= sort_link @q, :object_type, "Object Type" %></th>
						<th class="hidden-phone"><%= sort_link @q, :macro_id, "Macro" %></th>
						<% if can? :destroy, AxeMaster %>
						<th><%= t '.actions', :default => t("helpers.actions") %></th>
						<% end %>
					</tr>
				</thead>
				<tbody>
					<% @axe_masters.each do |axe_master| %>
					<tr>
						<% if axe_master.confirmed %>
							<td><%= link_to axe_master.seq_no, axe_master_path(axe_master) %></td>
							<td><%= link_to axe_master.museum_ref, axe_master_path(axe_master) %></td>
							<td class="hidden-phone"><%= axe_master.collections_id %></td>
							<td class="hidden-phone"><%= axe_master.townland %></td>
							<td class="hidden-phone"><%= axe_master.county %></td>
							<td class="hidden-phone"><%= axe_master.object_type %></td>
							<td class="hidden-phone"><%= axe_master.macro_id %></td>
							<% if can? :update, axe_master %>
								<td> <%= link_to t('.edit', :default => t("helpers.links.edit")),
								edit_axe_master_path(axe_master), :class => 'btn btn-mini' %>
							<% end %>
							<% if can? :destroy, axe_master %>
								<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
								axe_master_path(axe_master),
								:method => :delete,
								:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
								:class => 'btn btn-mini btn-danger' %> </td>
							<% end %>
						<% end %>
					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="pagination pagination-centered">
			<%= will_paginate @axe_masters %>
		</div>
	</div>
</div>

<% if can? :create, AxeMaster %>
	<%= link_to t('.new', :default => t("helpers.links.new")),
	new_axe_master_path,
	:class => 'btn btn-primary' %>
<% end %>

app/views/axe_masters/new.html.erb
<%- model_class = AxeMaster -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New Axe Record") %></h1>
</div>
<%= render :partial => 'form' %>