config/routes.rb
DiscoveryProgramme::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :users
  root :to => 'pages#home'
  
  resources :users, :bibliographies, :blade_profiles, :butt_shapes, :collections, :contexts, :cross_sections, :edge_forms, :edge_shapes, :face_shapes, :haftings, :macros, :prime_treatments, :profiles, :re_uses, :use_wears, :stray_axes
  resources :linkages, :pictures, :minerals, :chemical_compositions
  resources :axe_masters do
    collection { post :search, to: 'axe_masters#index'
       get :search, to: 'axe_masters#index' }
  end
  
  match '/list' => 'pages#list'
  match '/help' => 'pages#help'

  get "axe_masters/search"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :receive_emails, :remember_me, :name, :address, :institution, :phone, :purpose_of_use
  
  has_many :axe_masters, :foreign_key => "user_id", :primary_key => "id"
  has_many :pictures
  
  validates :email, :uniqueness => true, :presence => true
  validates :name, :presence => true
  validates :institution, :presence => true
  validates :purpose_of_use, :presence => true
  
  after_initialize :default_values

  after_create :send_admin_mail
  def send_admin_mail
      UserMailer.newUserConfirmation.deliver
  end

  
private
    def default_values
      self.admin ||= false
      self.researcher ||= false
      self.confirmed ||= false
      self.receive_emails ||= true
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
  end

  def show
  	@user=User.find(params[:id])
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:confirmed) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:admin) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:researcher) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:address) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:institution) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:phone) %></th>
      <th class="hidden-phone"><%= model_class.human_attribute_name(:purpose_of_use) %></th>
      <% if can? :destroy, User %>
      	<th class="hidden-phone"><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.email %></td>
        <td class="hidden-phone"><%= user.confirmed %></td>
        <td class="hidden-phone"><%= user.admin %></td>
        <td class="hidden-phone"><%= user.researcher %></td>
        <td class="hidden-phone"><%= user.address %></td>
        <td class="hidden-phone"><%= user.institution %></td>
        <td class="hidden-phone"><%= user.phone %></td>
        <td class="hidden-phone"><%= user.purpose_of_use %></td>
        <% if can? :destroy, User%>
	        <td class="hidden-phone">
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                      edit_user_path(user), :class => 'btn btn-mini' %>
	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                      user_path(user),
	                      :method => :delete,
	                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= "#{@user.name.capitalize}" %><br />
  <% if !@user.confirmed && (can? :destroy, User) %>
  <%= link_to "Confirm User", confirm_user_admin_user_path(@user), :class => 'btn btn-success btn-large' %>
    <%= link_to t('.destroy', :default => "Delete User"), admin_user_path, :method => 'delete',
          :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger btn-large' %> 
<% end %>
 </h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @user.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:institution) %>:</strong></dt>
  <dd><%= @user.institution %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @user.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:purpose_of_use) %>:</strong></dt>
  <dd><%= @user.purpose_of_use %></dd>

  <% unless @user.axe_masters.empty? %>
  	<div class="well">
	  	<dt><strong><%= "#{@user.name}'s records" %></strong></dt>
	  	<dd></dd>
	  	<% @user.axe_masters.each do |axe| %>
	  		<% if axe.confirmed %>
	  		<dt><strong>Seq No: </strong></dt>
	  		<dd><%= link_to axe.seq_no, axe_master_path(axe) %></dd>
	  		<% end %>
	  	<% end %>
  	</div>
  <% end %>
</dl>