config/routes.rb
DiscoveryProgramme::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :users
  root :to => 'pages#home'
  
  resources :users, :bibliographies, :blade_profiles, :butt_shapes, :collections, :contexts, :cross_sections, :edge_forms, :edge_shapes, :face_shapes, :haftings, :macros, :prime_treatments, :profiles, :re_uses, :use_wears, :stray_axes
  resources :linkages, :pictures, :minerals, :chemical_compositions
  resources :axe_masters do
    collection { post :search, to: 'axe_masters#index'
       get :search, to: 'axe_masters#index' }
  end
  
  match '/list' => 'pages#list'
  match '/help' => 'pages#help'

  get "axe_masters/search"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :description, :document_name, :document_type, :seq_no, :image, :user_id, :confirmed
  belongs_to :axe_master, :primary_key => "seq_no", :foreign_key => "seq_no"
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
  validates :description, :presence => true
  validates :document_name, :presence => true
  validates :document_type, :presence => true
  #validates :image, :presence => true
  
  after_initialize :default_values

  def ext_name
    @ext_name = self.image_url.split(".")
    if @ext_name.last
      return @ext_name.last
    else
      return ""
    end
  end

  def ext_type
    if ext_name == "jpg" || ext_name == "jpeg" || ext_name == "gif" || ext_name == "png" 
      return "image"
    elsif ext_name == "doc" || ext_name == "docx"
      return "document"
    elsif ext_name == "pdf"
      return "pdf"
    else
      return "misc" 
    end
  end
  
private
    def default_values
      self.confirmed ||= false
    end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @pictures = Picture.find(params[:id])
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  
  def create
    @picture = Picture.new(params[:picture])
      if @picture.save
        flash[:success] = "Document successfully uploaded. Note: Document must be confirmed by researcher before you can see it"
        UserMailer.signupConfirmation(current_user, "Document", @picture.axe_master).deliver
        redirect_to :back
      else
        flash[:alert] = "Error uploading document"
        redirect_to axe_master_path(@picture.axe_master)
      end
  end
  
  def update
    if @picture.update_attributes(params[:picture])
      flash[:notice] = "Record was successfully updated."
      redirect_to axe_master_path(@picture.axe_master)
    end
  end
  
  def destroy
    @axe = AxeMaster.find_by_seq_no(@picture.seq_no)
    @picture.destroy
    flash[:success] = "Picture successfully deleted"
    redirect_to axe_master_path(@axe)
  end


  def download
    send_file @picture.image, :type=>"pdf"
  end 

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/edit.html.erb
	<div class = "form-horizontal well">
		<fieldset>
			<legend>Edit picture</legend>
			<%= simple_form_for @picture, :html => {:multipart => true} do |f| %>
			  <%= f.input :document_name %>
			  <%= f.input :description %>
			  <%= f.input :document_type %>
			  <%= f.label :image %>
			  <%= f.file_field :image %> <br />
			<div class = "form-actions">
			  <%= f.button :submit, :class => "btn btn-primary" %>
			</div
			<% end %>
			
		</fieldset>
	</div>

app/views/pictures/show.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Documents" %><br />
  	<% if current_user && (current_user.researcher || current_user.admin) && !@picture.confirmed %>
		<%= link_to "Confirm Document", confirm_admin_picture_path(@picture), :class => 'btn btn-success btn-large' %>
    <%= link_to t('.destroy', :default => "Delete Document"), picture_path(@picture), :method => 'delete',
          :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger btn-large' %> 
    <%= link_to "Download Document", @picture.image.to_s, class: 'btn btn-info btn-large' %>
	<% end %>
  </h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:seq_no) %>:</strong></dt>
  <dd><%= @picture.seq_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:document_name) %>:</strong></dt>
  <dd><%= @picture.document_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:document_type) %>:</strong></dt>
  <dd><%= @picture.document_type %></dd>
</dl>

<% if @picture.document_type == "Image" %>
  <p><%= link_to "Download Document", @picture.image.to_s, class: 'btn btn-info' %></p>
  <%= image_tag @picture.image.to_s %>
<% else %>
  <%= link_to "Download", @picture.image.to_s %>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              :back, :class => 'btn'  %>
  <% if can? :update, @picture %>
	  <%= link_to t('.edit', :default => t("helpers.links.edit")),
	              edit_picture_path(@picture), :class => 'btn' %>
  <% end %>
  <% if can? :destroy, @picture %>
	  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	              picture_path(@picture),
	              :method => 'delete',
	              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
	              :class => 'btn btn-danger' %>
  <% end %>	              
</div>