config/routes.rb
DiscoveryProgramme::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :users
  root :to => 'pages#home'
  
  resources :users, :bibliographies, :blade_profiles, :butt_shapes, :collections, :contexts, :cross_sections, :edge_forms, :edge_shapes, :face_shapes, :haftings, :macros, :prime_treatments, :profiles, :re_uses, :use_wears, :stray_axes
  resources :linkages, :pictures, :minerals, :chemical_compositions
  resources :axe_masters do
    collection { post :search, to: 'axe_masters#index'
       get :search, to: 'axe_masters#index' }
  end
  
  match '/list' => 'pages#list'
  match '/help' => 'pages#help'

  get "axe_masters/search"

end

app/models/axe_master.rb
class AxeMaster < ActiveRecord::Base  
  attr_accessible :confirmed, :seq_no, :dating_information, :museum_ref, :collections_id, :current_location, :townland, :area, :county, :discovery_circumstances, :context_id, :from_year, :to_year, :map_reference, :temp_map_reference, :NGR_x_axis, :NGR_y_axis, :ordinance_datum, :object_type, :length, :width, :thickness, :weight, :face_shape_id, :cross_section_id, :edge_shape_id, :profile_id, :blade_profile_id, :butt_shape_id, :facet_1_right, :facet_2_right, :facet_1_left, :facet_2_left, :prime_treatment_id, :blade_ground, :sides_ground, :faces_ground, :butt_ground, :blade_polished, :sides_polished, :faces_polished, :butt_polished, :hafting_id, :description, :macro_id, :micro_id, :specific_gravity, :petrology, :comments, :drawn, :archival_complete, :object_comp, :petrology_comp, :mapping_comp, :photographed, :axe_cored, :barony, :parish, :hoard, :new_museum_ref, :catalogue_ref, :site_type, :secure_context, :feature_context_details, :associated_artifacts, :associated_features, :use_wear_id, :deliberate_breaking, :re_use_id, :edge_form_id, :edge_form, :mineral_identification_method, :chemical_composition_method, :object_status, :incomplete_description, :roughout_description, :incomplete_details, :roughout_details, :minature, :user_id, :image  
  validates_uniqueness_of :seq_no
  
  has_many :linkages, :dependent => :destroy, :foreign_key => "sequence_no", :primary_key => "seq_no"
  has_many :bibliographies, :class_name => "Bibliography", :through => :linkages
  has_many :pictures, :dependent => :destroy, :foreign_key => "seq_no", :primary_key => "seq_no"
  has_many :location_links, foreign_key: "seq_no", primary_key: "seq_no"
  has_many :townlands, class_name: "Townland", through: :location_links

  has_one :context, :foreign_key => :code, :primary_key => :context_id
  has_one :face_shape, :foreign_key => :code, :primary_key => :face_shape_id
  has_one :cross_section, :foreign_key => :code, :primary_key => :cross_section_id
  has_one :edge_shape, :foreign_key => :code, :primary_key => :edge_shape_id
  has_one :profile, :foreign_key => "code", :primary_key => "profile_id"
  has_one :blade_profile, :foreign_key => :code, :primary_key => :blade_profile_id
  has_one :butt_shape, :foreign_key => :code, :primary_key => :butt_shape_id
  has_one :prime_treatment, :foreign_key => :code, :primary_key => :prime_treatment_id
  has_one :hafting, :foreign_key => :code, :primary_key => :hafting_id
  has_one :macro, :foreign_key => :macro_id, :primary_key => :macro_id
  has_one :use_wear, :foreign_key => :code, :primary_key => :use_wear_id
  has_one :re_use, :foreign_key => :code, :primary_key => :re_use_id
  has_one :edge_form, :foreign_key => :code, :primary_key => :edge_form_id
  has_one :collection, :foreign_key => :collection_title, :primary_key => :collection_title
  has_one :user, :foreign_key => "id", :primary_key => "user_id"

  def self.ransackable_attributes(auth_object = nil)
      super & ["sequence_no", "museum_ref", "collections_id", "townland", "area", "county", "discovery_circumstances", "context_id", "from_year", "to_year", "map_reference", "temp_map_reference", "'NGR_x_axis'", "'NGR_y_axis'", "ordinance_datum", "object_type", "length", "width", "thickness", "weight", "face_shape_id", "cross_section_id", "edge_shape_id", "profile_id", "blade_profile_id", "butt_shape_id", "facet_1_right", "facet_2_right", "facet_1_left", "facet_2_left", "prime_treatment_id", "blade_ground", "sides_ground", "faces_ground", "butt_ground", "blade_polished", "sides_polished", "faces_polished", "butt_polished", "hafting_id", "description", "macro_id", "micro_id", "specific_gravity", "petrology", "drawn", "archival_complete", "object_comp", "petrology_comp", "mapping_comp", "photographed", "axe_cored", "barony", "parish", "hoard", "new_museum_ref", "catalogue_ref", "site_type", "secure_context", "feature_context_details", "associated_artifacts", "associated_features", "dating_information", "use_wear_id", "deliberate_breaking", "re_use_id", "edge_form_id", "mineral_identification_method", "chemical_composition_method", "object_status", "incomplete_description", "roughout_description", "incomplete_details", "roughout_details", "minature"]

  end
  
  after_initialize :default_values

  comma :researcher do
    seq_no
    museum_ref
    collections_id
    townland
    area
    county
    discovery_circumstances
    context_id
    from_year
    to_year
    map_reference
    temp_map_reference
    "NGR_x_axis"
    "NGR_y_axis"
    ordinance_datum
    object_type
    length
    width
    thickness
    weight
    face_shape_id
    cross_section_id
    edge_shape_id
    profile_id
    blade_profile_id
    butt_shape_id
    facet_1_right
    facet_2_right
    facet_1_left
    facet_2_left
    prime_treatment_id
    blade_ground
    sides_ground
    faces_ground
    butt_ground
    blade_polished
    sides_polished
    faces_polished
    butt_polished
    hafting_id
    description
    macro_id
    micro_id
    specific_gravity
    petrology
    drawn
    archival_complete
    object_comp
    petrology_comp
    mapping_comp
    photographed
    axe_cored
    barony
    parish
    hoard
    new_museum_ref   
    catalogue_ref
    site_type
    secure_context
    feature_context_details
    associated_artifacts
    associated_features
    dating_information
    use_wear_id
    deliberate_breaking
    re_use_id
    edge_form_id
    mineral_identification_method
    chemical_composition_method
    object_status
    incomplete_description
    roughout_description
    incomplete_details
    roughout_details
    minature
    
  end
  
  comma do
    seq_no
    museum_ref
    collections_id
    current_location
    townland
    area
    county
    discovery_circumstances
    context_id
    from_year
    to_year
    map_reference
    temp_map_reference
    "NGR_x_axis"
    "NGR_y_axis"
    ordinance_datum
    object_type
    length
    width
    thickness
    weight
    face_shape_id
    cross_section_id
    edge_shape_id
    profile_id
    blade_profile_id
    butt_shape_id
    facet_1_right
    facet_2_right
    facet_1_left
    facet_2_left
    prime_treatment_id
    blade_ground
    sides_ground
    faces_ground
    butt_ground
    blade_polished
    sides_polished
    faces_polished
    butt_polished
    hafting_id
    description
    macro_id
    micro_id
    specific_gravity
    petrology
    comments
    drawn
    archival_complete
    object_comp
    petrology_comp
    mapping_comp
    photographed
    axe_cored
    barony
    parish
    hoard
    new_museum_ref   
    catalogue_ref
    site_type
    secure_context
    feature_context_details
    associated_artifacts
    associated_features
    dating_information
    use_wear_id
    deliberate_breaking
    re_use_id
    edge_form_id
    mineral_identification_method
    chemical_composition_method
    object_status
    incomplete_description
    roughout_description
    incomplete_details
    roughout_details
    minature    
  end
  
  
private
    def default_values
      self.confirmed ||= false
      self.sequence_no ||= self.seq_no.to_i
      #self.seq_no ||= AxeMaster.order("seq_no desc").first.seq_no.to_i + 1
    end
end

app/models/bibliography.rb
class Bibliography < ActiveRecord::Base
  attr_accessible :author, :book_title, :linkage_id, :publication, :published_reference_in_year, :title, :where_published, :year

  has_many :linkages, :dependent => :destroy, :foreign_key => "bibliography_id", :primary_key => "linkage_id"  
  has_many :axe_masters, :through => :linkages

  comma do
  	author
 	book_title
 	linkage_id
 	publication
 	published_reference_in_year
 	title
 	where_published
 	year 	
  end
end

app/controllers/bibliographies_controller.rb
class BibliographiesController < ApplicationController
  load_and_authorize_resource

  def index
    @axe_master = AxeMaster.find_by_seq_no(params[:seq_no])
    @linkage = Linkage.new

    respond_to do |format|
      format.html
      format.xml {
        send_data @bibliographies.to_xml, :filename => "bibliographies.xml"
      }
      format.csv {
        send_data @bibliographies.to_comma, :col_sep => ',', :filename => "bibliographies.csv"
      }
    end

  end

  def show
  end
  
  
  def edit
    
  end
  
  def new
    
  end
  
  def create
    @bibliography = Bibliography.new(params[:bibliography])
    if @bibliography.save
      flash[:success] = "Your record has been created"
      redirect_to bibliographies_path
    else
      flash[:error] = "Record did not save"
      redirect_to :back
    end
  end

  def update
    @bibliography = Bibliography.find(params[:id])

    if @bibliography.update_attributes(params[:bibliography])
      flash[:notice] = "Record was successfully updated."
      redirect_to bibliography_path(@bibliography)
    end
  end
  
  def destroy
    @bibliography.destroy
    flash[:error] = "Bibliography deleted!"
    redirect_to bibliographies_path
  end  
end

app/helpers/bibliographies_helper.rb
module BibliographiesHelper
end

app/views/bibliographies/_form.html.erb
<%= simple_form_for @bibliography, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :author %>
  <%= f.input :year %>
  <%= f.input :title %>
  <%= f.input :book_title %>
  <%= f.input :publication %>
  <%= f.input :where_published %>
  <%= f.input :published_reference_in_year %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bibliographies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bibliographies/edit.html.erb
<%- model_class = Bibliography -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bibliographies/index.html.erb
<%- model_class = Bibliography -%>
<div class="page-header">
  <% if @axe_master %>
    <h1><%= "Add bibliography to Axe number #{@axe_master.seq_no}" %></h1>
  <% else %>
    <h1>Bibliography</h1>
  <% end %> 
</div>

<div class="row-fluid">
  <div class="span8"></div>
  <div class="span4">
      Export as: <%= link_to "XML", bibliographies_path(format: "xml"), class: "btn btn-primary" %> <%= link_to "CSV", bibliographies_path(format: "csv"), class: "btn btn-primary" %>
  </div>
</div>
<%= form_for @linkage do |f| %>
    <table class="table table-striped">
      <thead>
        <tr>
          <% if @axe_master %>
            <th></th>
          <% end %>
          <th><%= model_class.human_attribute_name(:author) %></th>
          <th class="hidden-phone"><%= model_class.human_attribute_name(:year) %></th>
          <th><%= model_class.human_attribute_name(:title) %></th>
          <th class="hidden-phone"><%= model_class.human_attribute_name(:publication) %></th>
          <th class="hidden-phone"><%= model_class.human_attribute_name(:where_published) %></th>
          <th>Link Key</th>
          <% if can? :update, Bibliography %>
          	<th><%=t '.actions', :default => t("helpers.actions") %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @bibliographies.each do |bibliography| %>
          <tr>
          <% if @axe_master %>
            <%= f.hidden_field :sequence_no, :value => @axe_master.seq_no %>
            <td><%= check_box_tag "linkage[bibliography_ids][]", bibliography.linkage_id %></td>
          <% end %>
            <td><%= bibliography.author %></td>
            <td class="hidden-phone"><%= bibliography.year %></td>
            <td><%= link_to bibliography.title, bibliography_path(bibliography.id) %></td>
            <td class="hidden-phone"><%= link_to bibliography.publication, bibliography_path(bibliography) %></td>
            <td class="hidden-phone"><%= bibliography.where_published %></td>
            <td><%= bibliography.linkage_id %></td>
            <% if can? :update, Bibliography %>
    	        <td>
    	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
    	                      edit_bibliography_path(bibliography), :class => 'btn btn-mini' %>
    	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    	                      bibliography_path(bibliography),
    	                      :method => :delete,
    	                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
    	                      :class => 'btn btn-mini btn-danger' %>
    	        </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if @axe_master %>
      <div class="form-actions">
          <%= f.submit "Add to Axe Record" %>
      </div>
    <% end %>
  <% end %>

<% if can? :create, Bibliography %>
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_bibliography_path,
	            :class => 'btn btn-primary' %>
<% end %>	       

app/views/bibliographies/new.html.erb
<%- model_class = Bibliography -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bibliographies/show.html.erb
<%- model_class = Bibliography -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
	
	<div class = "well">
	<dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
	  <dd><%= @bibliography.author %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
	  <dd><%= @bibliography.year %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
	  <dd><%= @bibliography.title %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:book_title) %>:</strong></dt>
	  <dd><%= @bibliography.book_title %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:publication) %>:</strong></dt>
	  <dd><%= @bibliography.publication %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:where_published) %>:</strong></dt>
	  <dd><%= @bibliography.where_published %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:published_reference_in_year) %>:</strong></dt>
	  <dd><%= @bibliography.published_reference_in_year %></dd>
	  <dt><strong>Link Key:</strong></dt>
	  <dd><%= @bibliography.linkage_id %></dd>
	</dl>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bibliographies_path, :class => 'btn'  %>
<% if can? :update, Bibliography %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bibliography_path(@bibliography), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bibliography_path(@bibliography),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
<% end %>        
</div>